name: Release Drafter

on:
  push:
    branches:
      - master
  workflow_dispatch: # This allows manual triggering

jobs:
  release-drafter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-path: .github/release-drafter.yml
          token: ${{ secrets.GITHUB_TOKEN }}
