name: Release Drafter

on:
  push:
    branches:
      - main
  workflow_dispatch: # This allows manual triggering
    inputs:
        # Latest commit to include with the release. If omitted, use the latest commit on the main branch.
        sha:
          description: Commit SHA
          type: string

permissions:
  contents: write
  pull-requests: read

jobs:
  release-drafter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          commitish: ${{ inputs.sha || github.sha }}
          disable-autolabeler: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
